version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432
    networks:
      - matcha_network
    volumes:
      - matcha_dbdata:/var/lib/postgresql/data

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   container_name: matcha_frontend
  #   ports:
  #     - 5173:3000
  #   restart: always
  #   networks:
  #     - matcha_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: matcha_backend
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgresdb
    networks:
      - matcha_network
    volumes:
      - matcha_dbdata:/app/uploads

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgresdb
    env_file:
      - .env
    ports:
      - 5050:80
    networks:
      - matcha_network
  
  # nginx:
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile
  #   container_name: matcha_nginx
  #   ports:
  #     - 3000:3000
  #   restart: always
  #   depends_on:
  #     - frontend
  #     - backend
  #   networks:
  #     - matcha_network

networks:
  matcha_network:

volumes:
  matcha_dbdata:

