version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passnadi
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./database:/var/lib/postgresql/data
    networks:
      - matcha

  api:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - backend/.env
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    networks:
      - matcha

networks:
  matcha:
    name: matcha
    driver: bridge