version: '3.8'

volumes:
  - matcha_volumes:

networks:
  - matcha_network:

services:
  postgresdb:
    image: postgres
    restart: always
    env_file:
      - .env
    networks:
      - matcha_network

  backend:
    build: ./backend
    dockerfile: Dockerfile
    container_name: matcha_backend
    ports:
      - 8000:8000
    restart: always
    depends_on:
      - postgresdb
    networks:
      - matcha_network
    volumes:
      - matcha_volume:/app/uploads

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgresdb
      - backend
    env_file:
      - .env
    ports:
      5050:80
    networks:
      - matcha_network
