version: '3.8'

services:
  postgresdb:
    image: postgres
    restart: always
    env_file:
      - .env
      #environment:
      #POSTGRES_DB: matchadb
      #POSTGRES_USER: stronk
      #POSTGRES_PASSWORD: pass
    ports:
      - 5432:5432
    networks:
      - matcha_network
    volumes:
      - matcha_dbdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: matcha_backend
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - postgresdb
    networks:
      - matcha_network

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    depends_on:
      - postgresdb
    env_file:
      - .env
        #environment:
        #PGADMIN_DEFAULT_EMAIL: admin@example.com
        #PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    networks:
      - matcha_network

networks:
  matcha_network:

volumes:
  matcha_dbdata:

