# version: '3.8'

networks:
  matcha:
    driver: bridge
    name: matcha

services:
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    expose:
      - 5432
  
  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports:
      - "8080:80"
    depends_on:
      - postgres

  flyway:
    image: flyway/flyway:latest
    environment:
      FLYWAY_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      FLYWAY_USER: ${FLYWAY_USER}
      FLYWAY_PASSWORD: ${FLYWAY_USER}
    volumes:
      - ./migrations:/flyway/sql  # Mount the migrations directory
    depends_on:
      - postgres
  # api:
  #   build:
  #     context: backend
  #     dockerfile: Dockerfile
  #   container_name: api
  #   networks:
  #     - matcha
  #   env_file:
  #     - backend/.env
  #   depends_on:
  #     - postgres
  #   ports:
  #     - "8000:8000"
  #   restart: always
