build:
	@go build -o bin/matchaVgo cmd/main.go

run: build
	@./bin/matchaVgo

# run:
# 	@go run main.go auth.go api.go config.go db.go users.go posts.go store.go utils.go types.go

# test:
# 	@go test -v ./..